export const TICKET_CATEGORY = {
  ORDER: 'ORDER',
  PAYMENT: 'PAYMENT',
  SHIPPING: 'SHIPPING',
  RETURN: 'RETURN',
  REFUND: 'REFUND',
  PRODUCT: 'PRODUCT',
  ACCOUNT: 'ACCOUNT',
  PROMOTION: 'PROMOTION',
  TECHNICAL: 'TECHNICAL',
  OTHER: 'OTHER',
} as const;

export type TicketCategory = (typeof TICKET_CATEGORY)[keyof typeof TICKET_CATEGORY];
export const TICKET_CATEGORIES = Object.values(TICKET_CATEGORY);

export const TICKET_PRIORITY = {
  LOW: 'LOW',
  NORMAL: 'NORMAL',
  HIGH: 'HIGH',
  URGENT: 'URGENT',
} as const;

export type TicketPriority = (typeof TICKET_PRIORITY)[keyof typeof TICKET_PRIORITY];
export const TICKET_PRIORITIES = Object.values(TICKET_PRIORITY);

export const TICKET_STATUS = {
  OPEN: 'OPEN',
  IN_PROGRESS: 'IN_PROGRESS',
  WAITING_FOR_CUSTOMER: 'WAITING_FOR_CUSTOMER',
  WAITING_FOR_SUPPORT: 'WAITING_FOR_SUPPORT',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED',
} as const;

export type TicketStatus = (typeof TICKET_STATUS)[keyof typeof TICKET_STATUS];
export const TICKET_STATUSES = Object.values(TICKET_STATUS);

export const SENDER_TYPE = {
  CUSTOMER: 'CUSTOMER',
  STAFF: 'STAFF',
} as const;

export type SenderType = (typeof SENDER_TYPE)[keyof typeof SENDER_TYPE];

export const MESSAGE_TYPE = {
  MESSAGE: 'MESSAGE',
  INTERNAL_NOTE: 'INTERNAL_NOTE',
  SYSTEM: 'SYSTEM',
} as const;

export type MessageType = (typeof MESSAGE_TYPE)[keyof typeof MESSAGE_TYPE];

export const HISTORY_ACTION = {
  CREATED: 'CREATED',
  ASSIGNED: 'ASSIGNED',
  REASSIGNED: 'REASSIGNED',
  UNASSIGNED: 'UNASSIGNED',
  PRIORITY_CHANGED: 'PRIORITY_CHANGED',
  STATUS_CHANGED: 'STATUS_CHANGED',
  RESOLVED: 'RESOLVED',
  REOPENED: 'REOPENED',
  CLOSED: 'CLOSED',
} as const;

export type HistoryAction = (typeof HISTORY_ACTION)[keyof typeof HISTORY_ACTION];

export const SUPPORT_CONFIG = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 20,
  MAX_LIMIT: 100,
  MIN_SUBJECT_LENGTH: 5,
  MAX_SUBJECT_LENGTH: 160,
  MIN_MESSAGE_LENGTH: 1,
  MAX_MESSAGE_LENGTH: 5000,
  MIN_RESOLUTION_LENGTH: 5,
  MAX_RESOLUTION_LENGTH: 2000,
  REOPEN_WINDOW_DAYS: 7,
} as const;

export const ALLOWED_SUPPORT_STATUS_TRANSITIONS: Record<TicketStatus, readonly TicketStatus[]> = {
  [TICKET_STATUS.OPEN]: [
    TICKET_STATUS.IN_PROGRESS,
    TICKET_STATUS.WAITING_FOR_SUPPORT,
    TICKET_STATUS.RESOLVED,
    TICKET_STATUS.CLOSED,
  ],
  [TICKET_STATUS.IN_PROGRESS]: [
    TICKET_STATUS.WAITING_FOR_CUSTOMER,
    TICKET_STATUS.WAITING_FOR_SUPPORT,
    TICKET_STATUS.RESOLVED,
    TICKET_STATUS.CLOSED,
  ],
  [TICKET_STATUS.WAITING_FOR_CUSTOMER]: [
    TICKET_STATUS.WAITING_FOR_SUPPORT,
    TICKET_STATUS.IN_PROGRESS,
    TICKET_STATUS.RESOLVED,
    TICKET_STATUS.CLOSED,
  ],
  [TICKET_STATUS.WAITING_FOR_SUPPORT]: [
    TICKET_STATUS.IN_PROGRESS,
    TICKET_STATUS.WAITING_FOR_CUSTOMER,
    TICKET_STATUS.RESOLVED,
    TICKET_STATUS.CLOSED,
  ],
  [TICKET_STATUS.RESOLVED]: [
    TICKET_STATUS.CLOSED,
    TICKET_STATUS.OPEN,
    TICKET_STATUS.IN_PROGRESS,
  ],
  [TICKET_STATUS.CLOSED]: [
    TICKET_STATUS.OPEN,
    TICKET_STATUS.IN_PROGRESS,
  ],
};
