export const MIN_CART_ITEM_QUANTITY = 1;
export const MAX_CART_ITEM_QUANTITY = 99;
export const MAX_CART_DISTINCT_ITEMS = 50;

export const UNAVAILABLE_REASON = {
  VARIANT_INACTIVE: 'VARIANT_INACTIVE',
  PRODUCT_INACTIVE: 'PRODUCT_INACTIVE',
  CATEGORY_INACTIVE: 'CATEGORY_INACTIVE',
  BRAND_INACTIVE: 'BRAND_INACTIVE',
  VARIANT_NOT_FOUND: 'VARIANT_NOT_FOUND',
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
} as const;

export type UnavailableReason =
  (typeof UNAVAILABLE_REASON)[keyof typeof UNAVAILABLE_REASON];
