export const SHIPMENT_STATUS = {
  PENDING: 'PENDING',
  READY_TO_SHIP: 'READY_TO_SHIP',
  SHIPPED: 'SHIPPED',
  IN_TRANSIT: 'IN_TRANSIT',
  OUT_FOR_DELIVERY: 'OUT_FOR_DELIVERY',
  DELIVERED: 'DELIVERED',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
} as const;

export type ShipmentStatus = (typeof SHIPMENT_STATUS)[keyof typeof SHIPMENT_STATUS];

export const SHIPPING_METHOD_TYPE = {
  STANDARD: 'STANDARD',
  EXPRESS: 'EXPRESS',
  FREE_SHIPPING: 'FREE_SHIPPING',
  FREE_TIERED: 'FREE_TIERED',
  FLAT_RATE: 'FLAT_RATE',
  SAME_DAY: 'SAME_DAY',
  CUSTOM: 'CUSTOM',
} as const;

export type ShippingMethodType =
  (typeof SHIPPING_METHOD_TYPE)[keyof typeof SHIPPING_METHOD_TYPE];

export const CARRIER_TYPE = {
  TCS: 'TCS',
  LEOPARDS: 'LEOPARDS',
  DHL: 'DHL',
  FEDEX: 'FEDEX',
  TRAX: 'TRAX',
  M_AND_P: 'M_AND_P',
  LOCAL_COURIER: 'LOCAL_COURIER',
  MANUAL: 'MANUAL',
} as const;

export type CarrierType = (typeof CARRIER_TYPE)[keyof typeof CARRIER_TYPE] | string;

// Valid status transitions: from -> allowed next states
export const ALLOWED_SHIPMENT_TRANSITIONS: Record<
  ShipmentStatus,
  readonly ShipmentStatus[]
> = {
  [SHIPMENT_STATUS.PENDING]: [
    SHIPMENT_STATUS.READY_TO_SHIP,
    SHIPMENT_STATUS.CANCELLED,
  ],
  [SHIPMENT_STATUS.READY_TO_SHIP]: [
    SHIPMENT_STATUS.SHIPPED,
    SHIPMENT_STATUS.CANCELLED,
  ],
  [SHIPMENT_STATUS.SHIPPED]: [
    SHIPMENT_STATUS.IN_TRANSIT,
    SHIPMENT_STATUS.OUT_FOR_DELIVERY,
    SHIPMENT_STATUS.DELIVERED,
    SHIPMENT_STATUS.FAILED,
  ],
  [SHIPMENT_STATUS.IN_TRANSIT]: [
    SHIPMENT_STATUS.OUT_FOR_DELIVERY,
    SHIPMENT_STATUS.DELIVERED,
    SHIPMENT_STATUS.FAILED,
  ],
  [SHIPMENT_STATUS.OUT_FOR_DELIVERY]: [
    SHIPMENT_STATUS.DELIVERED,
    SHIPMENT_STATUS.FAILED,
  ],
  [SHIPMENT_STATUS.DELIVERED]: [],
  [SHIPMENT_STATUS.FAILED]: [],
  [SHIPMENT_STATUS.CANCELLED]: [],
};

// Shipment can only be cancelled before it is dispatched/shipped
export const CANCELLABLE_SHIPMENT_STATUSES: readonly ShipmentStatus[] = [
  SHIPMENT_STATUS.PENDING,
  SHIPMENT_STATUS.READY_TO_SHIP,
];
