export const ErrorCodes = {
  // Generic & Validation
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  NOT_FOUND: 'NOT_FOUND',
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  CONFLICT: 'CONFLICT',
  GONE: 'GONE',
  TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',


  // Database
  DATABASE_ERROR: 'DATABASE_ERROR',

  // Authentication Specific
  ERR_INVALID_CREDENTIALS: 'ERR_INVALID_CREDENTIALS',
  ERR_EMAIL_ALREADY_EXISTS: 'ERR_EMAIL_ALREADY_EXISTS',
  ERR_ACCOUNT_DISABLED: 'ERR_ACCOUNT_DISABLED',
  ERR_UNAUTHORIZED: 'ERR_UNAUTHORIZED',
  ERR_FORBIDDEN: 'ERR_FORBIDDEN',
  ERR_TOKEN_EXPIRED: 'ERR_TOKEN_EXPIRED',
  ERR_TOKEN_INVALID: 'ERR_TOKEN_INVALID',
  ERR_REFRESH_TOKEN_INVALID: 'ERR_REFRESH_TOKEN_INVALID',
  ERR_EMAIL_ALREADY_VERIFIED: 'ERR_EMAIL_ALREADY_VERIFIED',
  ERR_VERIFICATION_TOKEN_INVALID: 'ERR_VERIFICATION_TOKEN_INVALID',
  ERR_VERIFICATION_TOKEN_EXPIRED: 'ERR_VERIFICATION_TOKEN_EXPIRED',
  ERR_PASSWORD_RESET_TOKEN_INVALID: 'ERR_PASSWORD_RESET_TOKEN_INVALID',
  ERR_PASSWORD_RESET_TOKEN_EXPIRED: 'ERR_PASSWORD_RESET_TOKEN_EXPIRED',
  ERR_CURRENT_PASSWORD_INVALID: 'ERR_CURRENT_PASSWORD_INVALID',
  ERR_PASSWORD_SAME_AS_CURRENT: 'ERR_PASSWORD_SAME_AS_CURRENT',

  // User Profile & Address Specific
  ERR_USER_NOT_FOUND: 'ERR_USER_NOT_FOUND',
  ERR_ADDRESS_NOT_FOUND: 'ERR_ADDRESS_NOT_FOUND',
  ERR_ADDRESS_LIMIT_REACHED: 'ERR_ADDRESS_LIMIT_REACHED',
  ERR_INVALID_PHONE: 'ERR_INVALID_PHONE',
  ERR_INVALID_ADDRESS: 'ERR_INVALID_ADDRESS',
  ERR_PROFILE_UPDATE_INVALID: 'ERR_PROFILE_UPDATE_INVALID',

  // RBAC & Admin Staff Specific
  ERR_PERMISSION_REQUIRED: 'ERR_PERMISSION_REQUIRED',
  ERR_INVALID_ROLE: 'ERR_INVALID_ROLE',
  ERR_ADMIN_USER_NOT_FOUND: 'ERR_ADMIN_USER_NOT_FOUND',
  ERR_CANNOT_CHANGE_OWN_ROLE: 'ERR_CANNOT_CHANGE_OWN_ROLE',
  ERR_CANNOT_DISABLE_SELF: 'ERR_CANNOT_DISABLE_SELF',
  ERR_STAFF_EMAIL_ALREADY_EXISTS: 'ERR_STAFF_EMAIL_ALREADY_EXISTS',

  // Catalog (Categories & Brands) Specific
  ERR_CATEGORY_NOT_FOUND: 'ERR_CATEGORY_NOT_FOUND',
  ERR_CATEGORY_SLUG_EXISTS: 'ERR_CATEGORY_SLUG_EXISTS',
  ERR_CATEGORY_HAS_CHILDREN: 'ERR_CATEGORY_HAS_CHILDREN',
  ERR_PARENT_CATEGORY_NOT_FOUND: 'ERR_PARENT_CATEGORY_NOT_FOUND',
  ERR_CATEGORY_SELF_PARENT: 'ERR_CATEGORY_SELF_PARENT',
  ERR_CATEGORY_CYCLE: 'ERR_CATEGORY_CYCLE',
  ERR_CATEGORY_MAX_DEPTH: 'ERR_CATEGORY_MAX_DEPTH',
  ERR_CATEGORY_IN_USE: 'ERR_CATEGORY_IN_USE',
  ERR_BRAND_NOT_FOUND: 'ERR_BRAND_NOT_FOUND',
  ERR_BRAND_NAME_EXISTS: 'ERR_BRAND_NAME_EXISTS',
  ERR_BRAND_SLUG_EXISTS: 'ERR_BRAND_SLUG_EXISTS',
  ERR_BRAND_IN_USE: 'ERR_BRAND_IN_USE',

  // Catalog (Products & Variants) Specific
  ERR_PRODUCT_NOT_FOUND: 'ERR_PRODUCT_NOT_FOUND',
  ERR_PRODUCT_SLUG_EXISTS: 'ERR_PRODUCT_SLUG_EXISTS',
  ERR_PRODUCT_INVALID_CATEGORY: 'ERR_PRODUCT_INVALID_CATEGORY',
  ERR_CATEGORY_NOT_LEAF: 'ERR_CATEGORY_NOT_LEAF',
  ERR_CATEGORY_INACTIVE: 'ERR_CATEGORY_INACTIVE',
  ERR_PRODUCT_BRAND_NOT_FOUND: 'ERR_PRODUCT_BRAND_NOT_FOUND',
  ERR_PRODUCT_BRAND_INACTIVE: 'ERR_PRODUCT_BRAND_INACTIVE',
  ERR_PRODUCT_REQUIRES_ACTIVE_VARIANT: 'ERR_PRODUCT_REQUIRES_ACTIVE_VARIANT',
  ERR_PRODUCT_CANNOT_PUBLISH: 'ERR_PRODUCT_CANNOT_PUBLISH',
  ERR_PRODUCT_INVALID_STATUS: 'ERR_PRODUCT_INVALID_STATUS',
  ERR_VARIANT_NOT_FOUND: 'ERR_VARIANT_NOT_FOUND',
  ERR_VARIANT_SKU_EXISTS: 'ERR_VARIANT_SKU_EXISTS',
  ERR_VARIANT_DUPLICATE_ATTRIBUTES: 'ERR_VARIANT_DUPLICATE_ATTRIBUTES',
  ERR_VARIANT_INVALID_PRICE: 'ERR_VARIANT_INVALID_PRICE',
  ERR_VARIANT_COMPARE_PRICE_INVALID: 'ERR_VARIANT_COMPARE_PRICE_INVALID',
  ERR_VARIANT_INVALID_ATTRIBUTES: 'ERR_VARIANT_INVALID_ATTRIBUTES',

  // Cart Specific (Module 08)
  ERR_CART_ITEM_NOT_FOUND: 'ERR_CART_ITEM_NOT_FOUND',
  ERR_CART_ITEM_LIMIT_REACHED: 'ERR_CART_ITEM_LIMIT_REACHED',
  ERR_CART_QUANTITY_LIMIT: 'ERR_CART_QUANTITY_LIMIT',
  ERR_CART_VARIANT_NOT_FOUND: 'ERR_CART_VARIANT_NOT_FOUND',
  ERR_CART_VARIANT_UNAVAILABLE: 'ERR_CART_VARIANT_UNAVAILABLE',
  ERR_CART_PRODUCT_UNAVAILABLE: 'ERR_CART_PRODUCT_UNAVAILABLE',
  ERR_CART_INVALID_QUANTITY: 'ERR_CART_INVALID_QUANTITY',

  // Wishlist Specific (Module 09)
  ERR_WISHLIST_ITEM_NOT_FOUND: 'ERR_WISHLIST_ITEM_NOT_FOUND',
  ERR_WISHLIST_ITEM_LIMIT_REACHED: 'ERR_WISHLIST_ITEM_LIMIT_REACHED',
  ERR_WISHLIST_PRODUCT_NOT_FOUND: 'ERR_WISHLIST_PRODUCT_NOT_FOUND',
  ERR_WISHLIST_PRODUCT_UNAVAILABLE: 'ERR_WISHLIST_PRODUCT_UNAVAILABLE',

  // Inventory Specific (Module 10)
  ERR_INVENTORY_NOT_FOUND: 'ERR_INVENTORY_NOT_FOUND',
  ERR_INVENTORY_INVALID_QUANTITY: 'ERR_INVENTORY_INVALID_QUANTITY',
  ERR_INVENTORY_INSUFFICIENT_STOCK: 'ERR_INVENTORY_INSUFFICIENT_STOCK',
  ERR_INVENTORY_RESERVED_EXCEEDS_ON_HAND: 'ERR_INVENTORY_RESERVED_EXCEEDS_ON_HAND',
  ERR_INVENTORY_INVALID_THRESHOLD: 'ERR_INVENTORY_INVALID_THRESHOLD',
  ERR_INVENTORY_ADJUSTMENT_INVALID: 'ERR_INVENTORY_ADJUSTMENT_INVALID',
  ERR_VARIANT_HAS_INVENTORY_HISTORY: 'ERR_VARIANT_HAS_INVENTORY_HISTORY',
  ERR_CART_INSUFFICIENT_STOCK: 'ERR_CART_INSUFFICIENT_STOCK',

  // Checkout Specific (Module 11)
  ERR_CHECKOUT_NOT_FOUND: 'ERR_CHECKOUT_NOT_FOUND',
  ERR_CHECKOUT_EMPTY_CART: 'ERR_CHECKOUT_EMPTY_CART',
  ERR_CHECKOUT_EXPIRED: 'ERR_CHECKOUT_EXPIRED',
  ERR_CHECKOUT_INVALID_ADDRESS: 'ERR_CHECKOUT_INVALID_ADDRESS',
  ERR_CHECKOUT_ITEM_UNAVAILABLE: 'ERR_CHECKOUT_ITEM_UNAVAILABLE',
  ERR_CHECKOUT_INSUFFICIENT_STOCK: 'ERR_CHECKOUT_INSUFFICIENT_STOCK',
  ERR_CHECKOUT_RESERVATION_FAILED: 'ERR_CHECKOUT_RESERVATION_FAILED',
  ERR_CHECKOUT_INVALID_STATE: 'ERR_CHECKOUT_INVALID_STATE',
  ERR_CHECKOUT_PRICE_CHANGED: 'ERR_CHECKOUT_PRICE_CHANGED',

  // Orders Specific (Module 12)
  ERR_ORDER_NOT_FOUND: 'ERR_ORDER_NOT_FOUND',
  ERR_ORDER_CHECKOUT_NOT_FOUND: 'ERR_ORDER_CHECKOUT_NOT_FOUND',
  ERR_ORDER_CHECKOUT_INVALID: 'ERR_ORDER_CHECKOUT_INVALID',
  ERR_ORDER_CHECKOUT_EXPIRED: 'ERR_ORDER_CHECKOUT_EXPIRED',
  ERR_ORDER_ALREADY_EXISTS: 'ERR_ORDER_ALREADY_EXISTS',
  ERR_ORDER_INVENTORY_FINALIZATION_FAILED: 'ERR_ORDER_INVENTORY_FINALIZATION_FAILED',
  ERR_ORDER_INVALID_STATUS_TRANSITION: 'ERR_ORDER_INVALID_STATUS_TRANSITION',
  ERR_ORDER_CANNOT_CANCEL: 'ERR_ORDER_CANNOT_CANCEL',
  ERR_ORDER_ALREADY_CANCELLED: 'ERR_ORDER_ALREADY_CANCELLED',
  ERR_ORDER_INVALID_NOTE: 'ERR_ORDER_INVALID_NOTE',
  ERR_ORDER_PAID_CANCELLATION_REQUIRES_REFUND: 'ERR_ORDER_PAID_CANCELLATION_REQUIRES_REFUND',

  // Payments Specific (Module 13)
  ERR_PAYMENT_NOT_FOUND: 'ERR_PAYMENT_NOT_FOUND',
  ERR_PAYMENT_ORDER_ALREADY_PAID: 'ERR_PAYMENT_ORDER_ALREADY_PAID',
  ERR_PAYMENT_ORDER_NOT_PAYABLE: 'ERR_PAYMENT_ORDER_NOT_PAYABLE',
  ERR_PAYMENT_PROVIDER_UNAVAILABLE: 'ERR_PAYMENT_PROVIDER_UNAVAILABLE',
  ERR_PAYMENT_PROVIDER_ERROR: 'ERR_PAYMENT_PROVIDER_ERROR',
  ERR_PAYMENT_ATTEMPT_LIMIT: 'ERR_PAYMENT_ATTEMPT_LIMIT',
  ERR_PAYMENT_INVALID_SIGNATURE: 'ERR_PAYMENT_INVALID_SIGNATURE',
  ERR_PAYMENT_INVALID_METHOD: 'ERR_PAYMENT_INVALID_METHOD',
  ERR_PAYMENT_INVALID_ACTION: 'ERR_PAYMENT_INVALID_ACTION',
  ERR_PAYMENT_ALREADY_SUCCEEDED: 'ERR_PAYMENT_ALREADY_SUCCEEDED',

  // Shipping & Fulfillment Specific (Module 14)
  ERR_SHIPPING_METHOD_NOT_FOUND: 'ERR_SHIPPING_METHOD_NOT_FOUND',
  ERR_SHIPPING_METHOD_INACTIVE: 'ERR_SHIPPING_METHOD_INACTIVE',
  ERR_SHIPPING_METHOD_NOT_ELIGIBLE: 'ERR_SHIPPING_METHOD_NOT_ELIGIBLE',
  ERR_SHIPPING_METHOD_CODE_EXISTS: 'ERR_SHIPPING_METHOD_CODE_EXISTS',
  ERR_SHIPPING_INVALID_FEE: 'ERR_SHIPPING_INVALID_FEE',
  ERR_SHIPPING_INVALID_ESTIMATE: 'ERR_SHIPPING_INVALID_ESTIMATE',
  ERR_SHIPMENT_NOT_FOUND: 'ERR_SHIPMENT_NOT_FOUND',
  ERR_SHIPMENT_ALREADY_EXISTS: 'ERR_SHIPMENT_ALREADY_EXISTS',
  ERR_SHIPMENT_ORDER_NOT_FULFILLABLE: 'ERR_SHIPMENT_ORDER_NOT_FULFILLABLE',
  ERR_SHIPMENT_ORDER_PAYMENT_REQUIRED: 'ERR_SHIPMENT_ORDER_PAYMENT_REQUIRED',
  ERR_SHIPMENT_INVALID_STATUS_TRANSITION: 'ERR_SHIPMENT_INVALID_STATUS_TRANSITION',
  ERR_SHIPMENT_TRACKING_REQUIRED: 'ERR_SHIPMENT_TRACKING_REQUIRED',
  ERR_SHIPMENT_ALREADY_DELIVERED: 'ERR_SHIPMENT_ALREADY_DELIVERED',
  ERR_ORDER_ALREADY_SHIPPED: 'ERR_ORDER_ALREADY_SHIPPED',
};





export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes] | string;


