export const EMAIL_STATUS = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  SENT: 'SENT',
  FAILED: 'FAILED',
  CANCELLED: 'CANCELLED',
} as const;

export const EMAIL_PROVIDER = {
  TEST: 'TEST',
  SMTP: 'SMTP',
} as const;

export const EMAIL_ERROR_CODES = {
  ERR_EMAIL_NOT_FOUND: 'ERR_EMAIL_NOT_FOUND',
  ERR_EMAIL_INVALID_RECIPIENT: 'ERR_EMAIL_INVALID_RECIPIENT',
  ERR_EMAIL_TEMPLATE_NOT_FOUND: 'ERR_EMAIL_TEMPLATE_NOT_FOUND',
  ERR_EMAIL_TEMPLATE_DATA_INVALID: 'ERR_EMAIL_TEMPLATE_DATA_INVALID',
  ERR_EMAIL_PROVIDER_UNAVAILABLE: 'ERR_EMAIL_PROVIDER_UNAVAILABLE',
  ERR_EMAIL_SEND_FAILED: 'ERR_EMAIL_SEND_FAILED',
  ERR_EMAIL_ALREADY_SENT: 'ERR_EMAIL_ALREADY_SENT',
  ERR_EMAIL_MAX_ATTEMPTS_REACHED: 'ERR_EMAIL_MAX_ATTEMPTS_REACHED',
  ERR_EMAIL_RETRY_NOT_ALLOWED: 'ERR_EMAIL_RETRY_NOT_ALLOWED',
  ERR_EMAIL_INVALID_ACTION: 'ERR_EMAIL_INVALID_ACTION',
} as const;

export const EMAIL_MAX_ATTEMPTS = parseInt(process.env.EMAIL_MAX_ATTEMPTS || '5', 10);
