import { ROLES, Role } from './roles.js';
import { PERMISSIONS, Permission, ALL_PERMISSIONS } from './permissions.js';

export const ROLE_PERMISSIONS: Record<Role, readonly Permission[]> = {
  [ROLES.SUPER_ADMIN]: ALL_PERMISSIONS,

  [ROLES.ADMIN]: [
    // User management (excluding admin creation/role update)
    PERMISSIONS.USER_READ,
    PERMISSIONS.USER_UPDATE,
    PERMISSIONS.ADMIN_USER_READ,
    PERMISSIONS.ADMIN_USER_DISABLE,

    // Catalog & Products
    PERMISSIONS.CATEGORY_CREATE,
    PERMISSIONS.CATEGORY_READ,
    PERMISSIONS.CATEGORY_UPDATE,
    PERMISSIONS.CATEGORY_DELETE,
    PERMISSIONS.BRAND_CREATE,
    PERMISSIONS.BRAND_READ,
    PERMISSIONS.BRAND_UPDATE,
    PERMISSIONS.BRAND_DELETE,
    PERMISSIONS.PRODUCT_CREATE,
    PERMISSIONS.PRODUCT_READ,
    PERMISSIONS.PRODUCT_UPDATE,
    PERMISSIONS.PRODUCT_DELETE,
    PERMISSIONS.PRODUCT_PUBLISH,

    // Inventory
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVENTORY_UPDATE,

    // Orders & Fulfillment
    PERMISSIONS.ORDER_READ,
    PERMISSIONS.ORDER_UPDATE,
    PERMISSIONS.ORDER_CANCEL,
    PERMISSIONS.ORDER_FULFILL,

    // Returns & Refunds
    PERMISSIONS.RETURN_READ,
    PERMISSIONS.RETURN_APPROVE,
    PERMISSIONS.RETURN_REJECT,
    PERMISSIONS.REFUND_READ,

    // Reviews
    PERMISSIONS.REVIEW_READ,
    PERMISSIONS.REVIEW_MODERATE,

    // Promotions & Coupons
    PERMISSIONS.PROMOTION_CREATE,
    PERMISSIONS.PROMOTION_READ,
    PERMISSIONS.PROMOTION_UPDATE,
    PERMISSIONS.PROMOTION_DELETE,
    PERMISSIONS.COUPON_CREATE,
    PERMISSIONS.COUPON_READ,
    PERMISSIONS.COUPON_UPDATE,
    PERMISSIONS.COUPON_DELETE,

    // Support
    PERMISSIONS.SUPPORT_READ,
    PERMISSIONS.SUPPORT_UPDATE,

    // Analytics & Audit
    PERMISSIONS.ANALYTICS_READ,
    PERMISSIONS.AUDIT_READ,

    // Payments
    PERMISSIONS.PAYMENT_READ,
    PERMISSIONS.PAYMENT_CONFIRM,
    PERMISSIONS.PAYMENT_RECONCILE,

    // Shipping & Fulfillment
    PERMISSIONS.SHIPPING_READ,
    PERMISSIONS.SHIPPING_MANAGE,
    PERMISSIONS.SHIPPING_FULFILL,
  ],

  [ROLES.PRODUCT_MANAGER]: [
    PERMISSIONS.CATEGORY_CREATE,
    PERMISSIONS.CATEGORY_READ,
    PERMISSIONS.CATEGORY_UPDATE,
    PERMISSIONS.BRAND_CREATE,
    PERMISSIONS.BRAND_READ,
    PERMISSIONS.BRAND_UPDATE,
    PERMISSIONS.PRODUCT_CREATE,
    PERMISSIONS.PRODUCT_READ,
    PERMISSIONS.PRODUCT_UPDATE,
    PERMISSIONS.PRODUCT_DELETE,
    PERMISSIONS.PRODUCT_PUBLISH,
    PERMISSIONS.INVENTORY_READ,
  ],

  [ROLES.ORDER_MANAGER]: [
    PERMISSIONS.ORDER_READ,
    PERMISSIONS.ORDER_UPDATE,
    PERMISSIONS.ORDER_CANCEL,
    PERMISSIONS.ORDER_FULFILL,
    PERMISSIONS.RETURN_READ,
    PERMISSIONS.RETURN_APPROVE,
    PERMISSIONS.RETURN_REJECT,
    PERMISSIONS.REFUND_READ,
    PERMISSIONS.USER_READ,
    PERMISSIONS.PAYMENT_READ,
    PERMISSIONS.PAYMENT_RECONCILE,
    PERMISSIONS.SHIPPING_READ,
    PERMISSIONS.SHIPPING_FULFILL,
  ],

  [ROLES.INVENTORY_MANAGER]: [
    PERMISSIONS.PRODUCT_READ,
    PERMISSIONS.INVENTORY_READ,
    PERMISSIONS.INVENTORY_UPDATE,
    PERMISSIONS.INVENTORY_ADJUST,
  ],

  [ROLES.CUSTOMER_SUPPORT]: [
    PERMISSIONS.USER_READ,
    PERMISSIONS.ORDER_READ,
    PERMISSIONS.RETURN_READ,
    PERMISSIONS.SUPPORT_READ,
    PERMISSIONS.SUPPORT_UPDATE,
    PERMISSIONS.SUPPORT_ASSIGN,
    PERMISSIONS.SUPPORT_CLOSE,
    PERMISSIONS.REVIEW_READ,
    PERMISSIONS.PAYMENT_READ,
    PERMISSIONS.SHIPPING_READ,
  ],

  [ROLES.CUSTOMER]: [],
};

