export const ROLES = {
  CUSTOMER: 'CUSTOMER',
  SUPER_ADMIN: 'SUPER_ADMIN',
  ADMIN: 'ADMIN',
  PRODUCT_MANAGER: 'PRODUCT_MANAGER',
  ORDER_MANAGER: 'ORDER_MANAGER',
  INVENTORY_MANAGER: 'INVENTORY_MANAGER',
  CUSTOMER_SUPPORT: 'CUSTOMER_SUPPORT',
} as const;

export type Role = (typeof ROLES)[keyof typeof ROLES];

export const STAFF_ROLES: Role[] = [
  ROLES.ADMIN,
  ROLES.PRODUCT_MANAGER,
  ROLES.ORDER_MANAGER,
  ROLES.INVENTORY_MANAGER,
  ROLES.CUSTOMER_SUPPORT,
];
