export const NOTIFICATION_TYPE = {
  // Order Notifications
  ORDER_PLACED: 'ORDER_PLACED',
  ORDER_CONFIRMED: 'ORDER_CONFIRMED',
  ORDER_PROCESSING: 'ORDER_PROCESSING',
  ORDER_READY_TO_SHIP: 'ORDER_READY_TO_SHIP',
  ORDER_SHIPPED: 'ORDER_SHIPPED',
  ORDER_DELIVERED: 'ORDER_DELIVERED',
  ORDER_CANCELLED: 'ORDER_CANCELLED',

  // Payment Notifications
  PAYMENT_PENDING: 'PAYMENT_PENDING',
  PAYMENT_SUCCEEDED: 'PAYMENT_SUCCEEDED',
  PAYMENT_FAILED: 'PAYMENT_FAILED',
  PAYMENT_REFUNDED: 'PAYMENT_REFUNDED',
  PAYMENT_PARTIALLY_REFUNDED: 'PAYMENT_PARTIALLY_REFUNDED',

  // Shipping Notifications
  SHIPMENT_CREATED: 'SHIPMENT_CREATED',
  SHIPMENT_SHIPPED: 'SHIPMENT_SHIPPED',
  SHIPMENT_IN_TRANSIT: 'SHIPMENT_IN_TRANSIT',
  SHIPMENT_OUT_FOR_DELIVERY: 'SHIPMENT_OUT_FOR_DELIVERY',
  SHIPMENT_DELIVERED: 'SHIPMENT_DELIVERED',
  SHIPMENT_FAILED: 'SHIPMENT_FAILED',

  // Review Notifications
  REVIEW_PUBLISHED: 'REVIEW_PUBLISHED',
  REVIEW_HIDDEN: 'REVIEW_HIDDEN',
  REVIEW_REJECTED: 'REVIEW_REJECTED',

  // Return Notifications
  RETURN_REQUESTED: 'RETURN_REQUESTED',
  RETURN_APPROVED: 'RETURN_APPROVED',
  RETURN_REJECTED: 'RETURN_REJECTED',
  RETURN_RECEIVED: 'RETURN_RECEIVED',
  RETURN_REFUND_PENDING: 'RETURN_REFUND_PENDING',
  RETURN_COMPLETED: 'RETURN_COMPLETED',

  // Refund Notifications
  REFUND_SUCCEEDED: 'REFUND_SUCCEEDED',
  REFUND_FAILED: 'REFUND_FAILED',

  // Inventory & System Notifications
  LOW_STOCK_ALERT: 'LOW_STOCK_ALERT',
  SYSTEM: 'SYSTEM',
} as const;

export type NotificationType =
  (typeof NOTIFICATION_TYPE)[keyof typeof NOTIFICATION_TYPE];

export const NOTIFICATION_CATEGORY = {
  ORDER: 'ORDER',
  PAYMENT: 'PAYMENT',
  SHIPPING: 'SHIPPING',
  REVIEW: 'REVIEW',
  RETURN: 'RETURN',
  REFUND: 'REFUND',
  INVENTORY: 'INVENTORY',
  PROMOTION: 'PROMOTION',
  SYSTEM: 'SYSTEM',
} as const;

export type NotificationCategory =
  (typeof NOTIFICATION_CATEGORY)[keyof typeof NOTIFICATION_CATEGORY];

export const NOTIFICATION_RETENTION_DAYS = 90;

export const NOTIFICATION_PAGINATION = {
  DEFAULT_PAGE: 1,
  DEFAULT_LIMIT: 20,
  MAX_LIMIT: 100,
} as const;
