export const MAX_WISHLIST_ITEMS = 100;

export const UNAVAILABLE_REASON = {
  PRODUCT_NOT_FOUND: 'PRODUCT_NOT_FOUND',
  PRODUCT_DRAFT: 'PRODUCT_DRAFT',
  PRODUCT_INACTIVE: 'PRODUCT_INACTIVE',
  PRODUCT_ARCHIVED: 'PRODUCT_ARCHIVED',
  CATEGORY_INACTIVE: 'CATEGORY_INACTIVE',
  BRAND_INACTIVE: 'BRAND_INACTIVE',
  NO_ACTIVE_VARIANTS: 'NO_ACTIVE_VARIANTS',
} as const;

export type UnavailableReason =
  (typeof UNAVAILABLE_REASON)[keyof typeof UNAVAILABLE_REASON];
